### ISSUE TITLE
TAB complete throws error/warn

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [ajgeiss0702/ajQueue#23]
`1`) go to proxy (bungee) console and type in `leavequeue`
`2`) press tab to autocomplete

get the error (here it is):
```
[02:20:01] [main/INFO]: An internal error occurred whilst executing this command, please check the console log for details.
[02:20:01] [main/WARN]: Error in dispatching command
java.lang.ClassCastException: class net.md_5.bungee.command.ConsoleCommandSender cannot be cast to class net.md_5.bungee.api.connection.ProxiedPlayer (net.md_5.bungee.command.ConsoleCommandSender and net.md_5.bungee.api.connection.ProxiedPlayer are in unnamed module of loader 'app')
	at us.ajg0702.queue.platforms.bungeecord.BungeeMethods.senderToPlayer(BungeeMethods.java:58) ~[?:?]
	at us.ajg0702.queue.commands.commands.leavequeue.LeaveCommand.autoComplete(LeaveCommand.java:108) ~[?:?]
	at us.ajg0702.queue.platforms.bungeecord.commands.BungeeCommand.onTabComplete(BungeeCommand.java:26) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:225) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.tabCompleteCommand(PluginManager.java:268) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at io.github.waterfallmc.waterfall.console.ConsoleCommandCompleter.complete(ConsoleCommandCompleter.java:21) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4381) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4347) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3778) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:57) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e3cbb01:unknown]
```

**Comment by MotikaCraft-TheJoshua** [comment]
NOTE: i did not test tabbing this from ingame, i will test it when i can. if somebody tests it before me please post results

**Comment by ajgeiss0702** [comment]
This is not the place to report issues
