### ISSUE TITLE
Unexpected NullPointerException error

### ISSUE THREAD

**Issue by Cubxity** [ajgeiss0702/ajQueue#29]
## Error
```
[22:07:59 ERROR]: java.lang.NullPointerException: at index 511                                                                                               
[22:07:59 ERROR]:       at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229)                                                 
[22:07:59 ERROR]:       at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)                                                
[22:07:59 ERROR]:       at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213)                                                
[22:07:59 ERROR]:       at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353)                                                         
[22:07:59 ERROR]:       at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:265)                                                            
[22:07:59 ERROR]:       at us.ajg0702.queue.common.queues.QueueServerImpl.getQueue(QueueServerImpl.java:101)                                                 
[22:07:59 ERROR]:       at us.ajg0702.queue.common.QueueManagerImpl.sendMessage(QueueManagerImpl.java:507)                                                   
[22:07:59 ERROR]:       at us.ajg0702.queue.common.QueueManagerImpl.sendMessages(QueueManagerImpl.java:491)                                                  
[22:07:59 ERROR]:       at us.ajg0702.queue.common.TaskManager.lambda$scheduleAtFixedRate$0(TaskManager.java:140)                                            
[22:07:59 ERROR]:       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)                                                 
[22:07:59 ERROR]:       at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)                                                        
[22:07:59 ERROR]:       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)          
[22:07:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                         
[22:07:59 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                         
[22:07:59 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)       
```

## Steps to reproduce
Unknown.

## Environment
`Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)`

**Comment by ajgeiss0702** [comment]
This is not the place to get support
